# Depends - This is FastAPI's dependency injection system. It lets you say
# "before running this endpoint, run thi function and give me the result".
# You'll use it to inject the database session into every endpoint.
from fastapi import FastAPI, HTTPException, Depends
# Session is the type  hint for the database session object. You use it to tell
# Python (and your IDE) what type db is:
# def create_user (db: Session): <- db is a SQLAlchemy Session
# Without this type hint your code worls but your IDE won't give you autocomplete
# on db methods.
from sqlalchemy.orm import Session
# defines the shape of incoming request data
from pydantic import BaseModel
# imports your models file so SQLAlchemy knows about your tables
import models
# engine - the database connection, needed to create tables
# get_db - the session dependancy function wrote in database.py
from database import engine, get_db

# Creating the tables
# This is one of the most important lines in the file. Breaking it down:
# models.Base - the Base class all your models inherit from
# .metadata - contains all the table definitions SQLAlchemy collected
# from your models
# .create_all(bind = engine) - creates all tables in PostgreSQL if they don't exist yet
# This runs every time you start the server. But it's safe - it uses CREATE TABJE
# IF NOT EXISTS under the hood, so it never overwrites existing tables or data
# Server starts -> create_all() runs -> PostgreSQL already has "users" table?
# -> skip -> PostgreSQL missing "tasks" table? -> create it
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# Pydantic schemas vs SQLAlchemy models
# You have two different types of classes:

# SQLAlchemy model - represents database table
# class User(Base):
#     __tablename__ = "users"
#     id    = Column(Integer, primary_key=True)
#     name  = Column(String)
#     email = Column(String)

# Pydantic schema - represents API request/response data


class UserCreate(BaseModel):
    name: str
    email: str
    age: int = None
    city: str = None


class TaskCreate(BaseModel):
    title: str
    description: str = ''
    user_id: int
# They look similar but serve completely different purposes:
#            SQLAlchemy                Pydantic Schema
# Purpose    defines database table    defines API data shape
# Used for   reading/writing to DB     validating requests
# Has id     yes - generated by DB     no
# Lives in   models.py                 main.py

# The flow is:
# Request comes in (JSON) ->
# Pydantic validates it - UserCreate ->
# You create a SQLAlchemy object - models.User ->
# SQLAlchemy saves it to PostgreSql

# Notice UserCreate han no id - that's correct because the database generates it
# automatically. You'd never ask the user to send an id when creating something.
